// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFlashcards() {
  return window['go']['main']['App']['GetFlashcards']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SaveInterval(arg1) {
  return window['go']['main']['App']['SaveInterval'](arg1);
}

export function ShowBottomRightPopup() {
  return window['go']['main']['App']['ShowBottomRightPopup']();
}

export function TriggerPopupCheck() {
  return window['go']['main']['App']['TriggerPopupCheck']();
}

export function UpdateSRS(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSRS'](arg1, arg2, arg3);
}
