// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetFlashcards():Promise<Array<main.Word>>;

export function HideWindow():Promise<void>;

export function Login():Promise<main.Config>;

export function Logout():Promise<boolean>;

export function SaveInterval(arg1:number):Promise<boolean>;

export function ShowBottomRightPopup():Promise<void>;

export function TriggerPopupCheck():Promise<number>;

export function UpdateSRS(arg1:string,arg2:number,arg3:number):Promise<boolean>;
