// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDnd() {
  return window['go']['main']['App']['ClearDnd']();
}

export function CreateDeck(arg1) {
  return window['go']['main']['App']['CreateDeck'](arg1);
}

export function DeleteDeck(arg1) {
  return window['go']['main']['App']['DeleteDeck'](arg1);
}

export function FetchFlashcards() {
  return window['go']['main']['App']['FetchFlashcards']();
}

export function ForseRefreshWords() {
  return window['go']['main']['App']['ForseRefreshWords']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDecks() {
  return window['go']['main']['App']['GetDecks']();
}

export function GetDndStatus() {
  return window['go']['main']['App']['GetDndStatus']();
}

export function GetLaunchAtLoginStatus() {
  return window['go']['main']['App']['GetLaunchAtLoginStatus']();
}

export function GetWords() {
  return window['go']['main']['App']['GetWords']();
}

export function GetWordsAndDecks() {
  return window['go']['main']['App']['GetWordsAndDecks']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RenameDeck(arg1, arg2) {
  return window['go']['main']['App']['RenameDeck'](arg1, arg2);
}

export function ResetReviewTimer() {
  return window['go']['main']['App']['ResetReviewTimer']();
}

export function SaveAutoHideAfterCards(arg1) {
  return window['go']['main']['App']['SaveAutoHideAfterCards'](arg1);
}

export function SaveIdleFlashMinutes(arg1) {
  return window['go']['main']['App']['SaveIdleFlashMinutes'](arg1);
}

export function SaveInterval(arg1) {
  return window['go']['main']['App']['SaveInterval'](arg1);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SetDndMinutes(arg1) {
  return window['go']['main']['App']['SetDndMinutes'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetMChallengeMode(arg1) {
  return window['go']['main']['App']['SetMChallengeMode'](arg1);
}

export function SetWordDeckIds(arg1, arg2) {
  return window['go']['main']['App']['SetWordDeckIds'](arg1, arg2);
}

export function ShowAppCardWindow() {
  return window['go']['main']['App']['ShowAppCardWindow']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TriggerPopupCheck() {
  return window['go']['main']['App']['TriggerPopupCheck']();
}

export function UpdateSRS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSRS'](arg1, arg2, arg3, arg4);
}
