// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDnd() {
  return window['go']['main']['App']['ClearDnd']();
}

export function FetchFlashcards() {
  return window['go']['main']['App']['FetchFlashcards']();
}

export function ForseRefreshWords() {
  return window['go']['main']['App']['ForseRefreshWords']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDndStatus() {
  return window['go']['main']['App']['GetDndStatus']();
}

export function GetWords() {
  return window['go']['main']['App']['GetWords']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ResetReviewTimer() {
  return window['go']['main']['App']['ResetReviewTimer']();
}

export function SaveAutoHideOnAnswer(arg1) {
  return window['go']['main']['App']['SaveAutoHideOnAnswer'](arg1);
}

export function SaveInterval(arg1) {
  return window['go']['main']['App']['SaveInterval'](arg1);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SetDndMinutes(arg1) {
  return window['go']['main']['App']['SetDndMinutes'](arg1);
}

export function SetMChallengeMode(arg1) {
  return window['go']['main']['App']['SetMChallengeMode'](arg1);
}

export function ShowAppCardWindow() {
  return window['go']['main']['App']['ShowAppCardWindow']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TriggerPopupCheck() {
  return window['go']['main']['App']['TriggerPopupCheck']();
}

export function UpdateSRS(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSRS'](arg1, arg2, arg3);
}
