// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearDnd():Promise<boolean>;

export function CreateDeck(arg1:string):Promise<boolean>;

export function DeleteDeck(arg1:string):Promise<boolean>;

export function FetchFlashcards():Promise<Array<main.Word>>;

export function ForseRefreshWords():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetDecks():Promise<Array<main.Deck>>;

export function GetDndStatus():Promise<main.DndStatus>;

export function GetWords():Promise<Array<main.Word>>;

export function GetWordsAndDecks():Promise<main.WordsAndDecks>;

export function HideWindow():Promise<void>;

export function Login():Promise<main.Config>;

export function Logout():Promise<boolean>;

export function RenameDeck(arg1:string,arg2:string):Promise<boolean>;

export function ResetReviewTimer():Promise<void>;

export function SaveAutoHideOnAnswer(arg1:boolean):Promise<boolean>;

export function SaveInterval(arg1:number):Promise<boolean>;

export function SaveWindowState():Promise<void>;

export function SetDndMinutes(arg1:number):Promise<boolean>;

export function SetMChallengeMode(arg1:string):Promise<boolean>;

export function SetWordDeckIds(arg1:string,arg2:Array<string>):Promise<boolean>;

export function ShowAppCardWindow():Promise<void>;

export function ShowWindow():Promise<void>;

export function TriggerPopupCheck():Promise<number>;

export function UpdateSRS(arg1:string,arg2:number,arg3:number):Promise<boolean>;
